name = "Asciicast"
uuid = "2600d445-abca-43b9-92aa-ce144ac0b05b"
authors = ["Eric Hanson <5846501+ericphanson@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
